-- A definição correta de is_gerente_or_supervisor() (consultando `usuarios`,
-- não a `profiles` legada) foi movida para 000_schema_base.sql, pois a
-- função precisa existir ANTES de qualquer CREATE POLICY no script —
-- inclusive as de add_alunos_historico.sql, que roda logo após propostas.sql
-- e muito antes de aplicar_rls.sql. Este arquivo fica só como marcador de
-- histórico; nada a executar.
